export const equipo = [
  {
    foto: "/public/img/SandraRodriguez.png",
    nombre: "Sandra Rodriguez",
    rol: "Project Manager",
    linkedin: "https://www.linkedin.com/in/sandra-rodriguez-133687275/",
    pais: "Colombia",
  },
  {
    foto: "/public/img/FernandoVergel.png",
    nombre: "Fernando Vergel",
    rol: "UX/UI Designer",
    linkedin: "https://www.linkedin.com/in/fernandovergel/",
    pais: "Peru",
  },
  {
    foto: "/public/img/EmilianoLongo.png",
    nombre: "Emiliano Joaquín Longo",
    rol: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/emilianojlongo/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/JaimeAngel.png",
    nombre: "Jaime Orlando Angel Barreto",
    rol: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/jaimeangeldev/",
    pais: "Colombia",
  },
  {
    foto: "/public/img/GastonSalas.png",
    nombre: "Gaston Salas",
    rol: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/gastonsalas095/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/TobiasOlveira.png",
    nombre: "Tobias Olveira",
    rol: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/tobias-olveira-52a0311b7/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/LuzTabraj.png",
    nombre: "Luz Tabraj Briceño",
    rol: "QA Tester",
    linkedin: "https://www.linkedin.com/in/luz-tabraj/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/TomasSoto.png",
    nombre: "Tomás Soto",
    rol: "QA Tester",
    linkedin: "https://www.linkedin.com/in/tom%C3%A1s-soto-038709267/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/EliseoMontenegro.png",
    nombre: "Eliseo Montenegro",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/eliseo-montenegro/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/MarianaCuba.png",
    nombre: "Mariana Cuba",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/mariana-cuba-72a901258/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/SantiagoPerez.png",
    nombre: "Santiago perez kay",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/santiagoperezkay/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/ClaudiaOrtizChi.png",
    nombre: "Claudia Ortiz",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/claudia-ortiz-backend/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/LucianaMazur.png",
    nombre: "Luciana Mazur",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/lucianamazur/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/LeandroDeferrari.png",
    nombre: "Leandro Deferrari Arevalo",
    rol: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/leandrodeferrari/",
    pais: "Argentina",
  },
  {
    foto: "/public/img/AlejandraPanizza.png",
    nombre: "Alejandra Carla Panizza",
    rol: "Team Leader",
    linkedin: "https://www.linkedin.com/in/alejandra-carla-panizza/",
    pais: "Argentina",
  },
];
